import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins, Pacifico } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "./providers";
import { AppFrame } from "./components/AppFrame";
import { IPBanChecker } from "./components/IPBanChecker";
import { SuspensionGuard } from "./components/SuspensionGuard";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppins.variable} ${pacifico.variable} antialiased bg-[#1a1b23] text-[#e4e6eb] flex flex-col min-h-screen`}
          suppressHydrationWarning
        >
          <IPBanChecker />
          <SuspensionGuard />
          <Providers>
            <AppFrame>{children}</AppFrame>
          </Providers>
          <Analytics />
        </body>
      </html>
    </ClerkProvider>
  );
}
